
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 15 03:01:25 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 22;
  public static final int CloseTest = 8;
  public static final int Or = 9;
  public static final int CloseUntil = 12;
  public static final int Llave_c = 29;
  public static final int Op_booleano = 25;
  public static final int Throwln = 43;
  public static final int Llave_a = 28;
  public static final int Eat = 42;
  public static final int T_dato = 4;
  public static final int Define = 39;
  public static final int L = 40;
  public static final int Stop = 48;
  public static final int CloseFor = 15;
  public static final int Character = 6;
  public static final int Corchete_c = 31;
  public static final int Corchete_a = 30;
  public static final int Then = 10;
  public static final int OpenMatch = 45;
  public static final int Division = 20;
  public static final int Int = 5;
  public static final int Parentesis_c = 27;
  public static final int Parentesis_a = 26;
  public static final int EOF = 0;
  public static final int P_coma = 33;
  public static final int OpenUntil = 11;
  public static final int OpenTest = 7;
  public static final int error = 1;
  public static final int When = 47;
  public static final int As = 38;
  public static final int Linea = 2;
  public static final int Op_atribucion = 23;
  public static final int ERROR = 36;
  public static final int Do = 13;
  public static final int Op_logico = 21;
  public static final int Identificador = 34;
  public static final int Resta = 18;
  public static final int THrow = 44;
  public static final int Boolean = 41;
  public static final int Multiplicacion = 19;
  public static final int Op_incremento = 24;
  public static final int CloseMatch = 46;
  public static final int Numero = 35;
  public static final int CloseMain = 37;
  public static final int Suma = 17;
  public static final int Main = 32;
  public static final int Igual = 16;
  public static final int OpenFor = 14;
  public static final int Comillas = 3;
}

