
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 23;
  public static final int CloseTest = 9;
  public static final int Or = 10;
  public static final int Coma = 39;
  public static final int CloseUntil = 13;
  public static final int Llave_c = 33;
  public static final int Op_booleano = 27;
  public static final int Throwln = 48;
  public static final int Llave_a = 32;
  public static final int Eat = 47;
  public static final int T_dato = 5;
  public static final int Define = 44;
  public static final int L = 45;
  public static final int Stop = 53;
  public static final int CloseFor = 16;
  public static final int Character = 7;
  public static final int Corchete_c = 35;
  public static final int NOT = 56;
  public static final int AND = 54;
  public static final int Corchete_a = 34;
  public static final int Then = 11;
  public static final int OR = 55;
  public static final int OpenMatch = 50;
  public static final int Return = 24;
  public static final int Division = 21;
  public static final int Int = 6;
  public static final int Parentesis_c = 29;
  public static final int Parentesis_a = 28;
  public static final int P_coma = 37;
  public static final int EOF = 0;
  public static final int OpenUntil = 12;
  public static final int OpenTest = 8;
  public static final int error = 1;
  public static final int When = 52;
  public static final int As = 43;
  public static final int Linea = 2;
  public static final int CloseMethod = 31;
  public static final int Op_atribucion = 25;
  public static final int ERROR = 41;
  public static final int Do = 14;
  public static final int Op_logico = 22;
  public static final int OpenMethod = 30;
  public static final int Identificador = 38;
  public static final int Resta = 19;
  public static final int Caracter = 4;
  public static final int THrow = 49;
  public static final int Boolean = 46;
  public static final int Multiplicacion = 20;
  public static final int Op_incremento = 26;
  public static final int CloseMatch = 51;
  public static final int Numero = 40;
  public static final int CloseMain = 42;
  public static final int Suma = 18;
  public static final int Main = 36;
  public static final int Igual = 17;
  public static final int OpenFor = 15;
  public static final int Comillas = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Comillas",
  "Caracter",
  "T_dato",
  "Int",
  "Character",
  "OpenTest",
  "CloseTest",
  "Or",
  "Then",
  "OpenUntil",
  "CloseUntil",
  "Do",
  "OpenFor",
  "CloseFor",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Op_logico",
  "Op_relacional",
  "Return",
  "Op_atribucion",
  "Op_incremento",
  "Op_booleano",
  "Parentesis_a",
  "Parentesis_c",
  "OpenMethod",
  "CloseMethod",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "Main",
  "P_coma",
  "Identificador",
  "Coma",
  "Numero",
  "ERROR",
  "CloseMain",
  "As",
  "Define",
  "L",
  "Boolean",
  "Eat",
  "Throwln",
  "THrow",
  "OpenMatch",
  "CloseMatch",
  "When",
  "Stop",
  "AND",
  "OR",
  "NOT"
  };
}

