
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 14 20:54:29 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 20;
  public static final int CloseTest = 8;
  public static final int Or = 9;
  public static final int Throw = 42;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 23;
  public static final int Throwln = 41;
  public static final int Llave_a = 26;
  public static final int Eat = 40;
  public static final int T_dato = 4;
  public static final int Define = 37;
  public static final int L = 38;
  public static final int Character = 6;
  public static final int Corchete_c = 29;
  public static final int Corchete_a = 28;
  public static final int Then = 10;
  public static final int While = 12;
  public static final int Division = 18;
  public static final int Int = 5;
  public static final int Parentesis_c = 25;
  public static final int Parentesis_a = 24;
  public static final int For = 13;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int OpenTest = 7;
  public static final int error = 1;
  public static final int As = 36;
  public static final int Linea = 2;
  public static final int Op_atribucion = 21;
  public static final int Do = 11;
  public static final int ERROR = 34;
  public static final int Op_logico = 19;
  public static final int Identificador = 32;
  public static final int Resta = 16;
  public static final int Boolean = 39;
  public static final int Multiplicacion = 17;
  public static final int Op_incremento = 22;
  public static final int Numero = 33;
  public static final int CloseMain = 35;
  public static final int Suma = 15;
  public static final int Main = 30;
  public static final int Igual = 14;
  public static final int Comillas = 3;
}

